language: android
android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-25.0.3
    - platform-tools
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
- sudo chmod +x gradlew

script:
- ./gradlew test