language: android
android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-25.0.3
    - platform-tools
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
- sudo chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  - npm install -g firebase-tools

script:
- ./gradlew test

after_success:
  - firebase deploy --token $FIREBASE_TOKEN